### ISSUE TITLE
Add resource to search preferences

### ISSUE THREAD

**Issue by mattgmarcus** [LedgerSync/ledger_sync#107]
https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/preferences#read-preferences

I'd like the ability to pull out the preferences object from QBO, given a specific company.
This object is read only, since it is just a reflection of that company's preferences. I'm not sure if we want to handle this differently as a result. Like maybe we just return a hash of the data. This would be QBO specific.

Specifically I'd like to get the attributes `Preferences.AccountingInfoPrefs.ClassTrackingPerLine` and `Preferences.AccountingInfoPrefs.ClassTrackingPerTxn`

I'm not sure if their API docs are wrong by the way. For that link I put up top, for example, here's the names I see for the attributes
![image](https://user-images.githubusercontent.com/4755444/70749707-c06fe780-1ce1-11ea-919c-f65bf8a08faf.png)

But then in the Purchase section (https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/purchase), I see this different attribute `Preferences.AccountingInfoPrefs.ClassTrackingPerLine `
![image](https://user-images.githubusercontent.com/4755444/70749752-d8476b80-1ce1-11ea-9a92-ebed8ab9decd.png)

**Comment by ryanwjackson** [comment]
NetSuite also relies on custom fields as well.  Currently, we don't support this, as we have to name resource attributes explicitly.  This may be relevant here as we build a resource where we don't intend to be explicit, given that QBO preferences aren't the same (naming or way of managing) as NS.
