### ISSUE TITLE
Add ability to reference class and department in resources

### ISSUE THREAD

**Issue by mattgmarcus** [LedgerSync/ledger_sync#108]
For the resources we've worked on thus far (Purchase, Deposit, Transfer, etc.) let's add the ability to reference classes and departments on the resources. For some of them, the reference will be on the line item. For others, it will be on the parent resource.

**Comment by ryanwjackson** [comment]
If this takes a lot of work, just break it up into separate PRs per resource.

**Comment by mattgmarcus** [comment]
first 3
- deposit
- expense
- transfer (?)
