### ISSUE TITLE
Quickbooks Online `revoke_token!` method throwing exception

### ISSUE THREAD

**Issue by SeanBolt** [LedgerSync/ledger_sync#126]
**Describe the bug**
Quickbooks Online adaptor `revoke_token!` method throwing exception `An empty string is not a valid JSON string.`

**To Reproduce**
- Initialize quickbooks online adaptor
- Call `revoke_token!` method

**Expected behavior**
Quickbooks Online token to be revoked

**Additional context**
I dug into the oauth2 library and it seems the cause of this is a `401 Unauthorized` error

```
#<OAuth2::Response:0x00007fce36811c38 @response=#<Faraday::Response:0x00007fce36811cb0 @on_complete_callbacks=[], @env=#<Faraday::Env @method=:post @body="" @url=#<URI::HTTPS https://developer.api.intuit.com/v2/oauth2/tokens/revoke> @request=#<Faraday::RequestOptions (empty)> @request_headers={"User-Agent"=>"Faraday v0.17.1", "Accept"=>"application/json", "Content-Type"=>"application/json", "Authorization"=>"Bearer eyJlbmMiOiJBMTI4Q0JDLUhTMjU2IiwiYWxnIjoiZGlyIn0..xiQssIcX3gJZV36X9htQ7A.1JYqh4A7Cv3k_CFBtAj3pXOOm23agQ6qf8wtDTj4arwH5P9GhfRqME3C8M8clgCp14E2z_j-u4hM3-b821EmZ4vRU8k42qTctklxoy71PdbzSS4kAgAmWlyc_pmYyeBt-1J9xINaGUtU2LlWJn1FzQsHvqFICo5s-jA83-4vUykBeVBvBbAHnB-KA4h0V4bO3_uBUtG8Jkve2xCkrXQqDoAwOPwB4ymhnsW6XBJtwCeNz6NXZx4-TLUj_U0-pvd2WkGdw8EdUsbiHkpwJlCFqVoTrhCR3xtFxUw-tDD3N5MLyfNWRDpSTWOVy8a8a8T3IRtPiQaCHaEtu3fZdKPphpdmYuD6ovV7g5UO8p5fVbVkXmwrgKuRExYyJRV0VKTsCvAyPcxsRsaBvVFSdkrFBqKoet15Iq44KRSyugiK-IFwmdKM95r3vSZ8lYc-r9buKV1FMph9XJADyoVa0xlmwq7zmtygtgavzTK3ol147Esxp43Xk_7zk4EkXnc6y37Q2-ksfh2gCJbejcePGAT0URU95zLTXaSMDSFWCAompDm5j1LcgSVob3XjMkGuYYvm1oWXNy_wIpq-cf5FUMlvGFSmtsO8srRojYVldmIi_bNW7TXk1SioDAi7ePB_8_BBgbbW99Yop26CVk3xJ1RoJjd-8dkU9b1QGNq971RCaEL2ddnAESNPg-Ruze2eQ-yqc5f0gSQ65B54Ha3ePhUcHi0-mz3fZWzDO_5X52j7jOo.IKgKdI-akzXjnww8UGGrNg"} @ssl=#<Faraday::SSLOptions verify=true> @response=#<Faraday::Response:0x00007fce36811cb0 ...> @response_headers={"date"=>"Tue, 14 Jan 2020 18:26:47 GMT", "content-length"=>"0", "connection"=>"close", "server"=>"nginx", "strict-transport-security"=>"max-age=15552000", "intuit_tid"=>"ab39fd3d-62e1-4c5e-9300-0d94b70759ec", "cache-control"=>"no-cache", "pragma"=>"no-cache", "expires"=>"-1"} @status=401 @reason_phrase="Unauthorized">>, @options={:parse=>nil}>
```

![image](https://user-images.githubusercontent.com/8883915/72371143-96329080-36b8-11ea-9194-26b7c7f3a71b.png)

**Comment by SeanBolt** [comment]
On further investigation it may be connected to the use of the bearer token to authenticate - when I swap out the bearer token for basic auth (generated from client and secret keys) the request completes successfully with a 200 response.

**Comment by mattgmarcus** [comment]
Ah interesting. I do think I might remember seeing that the auth scheme was different for this. If that's the case, feel free to open up a PR changing this

**Comment by ryanwjackson** [comment]
@SeanBolt if you could please write a PR with how you changed the auth scheme, that would be great!

From [the docs]: https://developer.intuit.com/app/developer/qbo/docs/develop/authentication-and-authorization/oauth-2.0#revoke-token-disconnect

<img width="790" alt="Screen Shot 2020-01-15 at 12 35 19" src="https://user-images.githubusercontent.com/657902/72430783-80de6480-3793-11ea-824b-adda6ff81647.png">

Looks like it does need to be basic auth.
