### ISSUE TITLE
Resource support for Account (6 hrs)

### ISSUE THREAD

**Issue by mattgmarcus** [LedgerSync/ledger_sync#14]
https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/account

We need the ability to `Query` an account. This is only one that is needed for now, so we could just do the `Search` function.

Attribute-wise, we need the following

- Name
- AcctNum
- SubAccount
- Classification
- FullyQualifiedName
- CurrencyRef
- CurrentBalanceWithSubAccounts
- CurrentBalance
- Description
- Active
- AccountType
- AccountSubType

**Comment by ryanwjackson** [comment]
@mattgmarcus Just to clarify this is not the owner of the ledger, it's the account (like the revenue source)?

We will need to add an `Account` resource with these attributes and then add the `Searcher` for it.

@jozefvaclavik Do you have a sense offhand what we need to do to enable searchers to accept various attributes to search by?

**Comment by mattgmarcus** [comment]
Yeah I mean the account in the sense of the account in Quickbooks. Like your SVB Bank account, Brex card, etc.
In QBO, it'd be for this resource https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/account

I know their API supports search decently well

**Comment by ryanwjackson** [comment]
I guess I'm wondering if there's a better resource name than `Account`, as that is confusing IMO.  But absent better ideas, then yeah, we can go with that.

**Comment by mattgmarcus** [comment]
Got it. You could call it `LedgerAccount`. 
Also, `account` as it is sort of represents an organization/company within ledger sync. So it could be a good idea to just rename that, since `account` is a rigged word in the accounting world

**Comment by ryanwjackson** [comment]
What could we rename it to that wouldn't be recognized in the accounting world?  Because account, customer are taken.  I'm also less concerned in the app, given that references to this account is scoped to `LedgerSync::Account`.  I say we start with `LedgerSync::Account`, and can easily change before merging if we come up with something better.

**Comment by mattgmarcus** [comment]
We say “organization” in our app. That could work.

**Comment by ryanwjackson** [comment]
Ok, created: https://github.com/LedgerSync/temp_app/issues/11

We will use `Account` here.

@jozefvaclavik I'm going to assign to you.  Can you add an estimate to the title and then get started on a PR?
