### ISSUE TITLE
Add NetSuite Department resource

### ISSUE THREAD

**Issue by ryanwjackson** [LedgerSync/ledger_sync#154]
- [x] operations
  - [x] create
  - [x] delete
  - [x] find
  - [x] update
- [x] searcher
- [x] qa tests

https://www.netsuite.com/help/helpcenter/en_US/srbrowser/Browser2019_2/script/record/department.html

**Comment by SeanBolt** [comment]
@ryanwjackson are we planning to add Department to the `Netsuite adaptor`, `Netsuite Soap adaptor` or both?

**Comment by ryanwjackson** [comment]
Just the netsuite rest adaptor for now.
