### ISSUE TITLE
NetSuite searcher: specified offset is out of bounds

### ISSUE THREAD

**Issue by SeanBolt** [LedgerSync/ledger_sync#173]
**Describe the bug**
A 404 `Specified offset is out of bounds` error occurs when using NS searchers. The desired behavior is to have the searcher return an empty result, similar to how QBO searchers work.

**Error**
We only have two department records in our sandbox, when we hit the `"/services/rest/record/v1/department?limit=999&offset=999"` enpoint the following error is returned:

```
{
    "type" => "https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.5",
    "title" => "Specified offset is out of bounds.",
    "status" => 404,
    "o:errorCode" => "NONEXISTENT_OFFSET"
}
```

**Additional context**
We're using searchers to return all relevant records, to do this we rely on the `searcher.next_searcher` method which increments the pagination queries. We break from the loop when the searcher returns an empty result.

**Comment by SeanBolt** [comment]
@ryanwjackson do we handle error codes like this anywhere else?

**Comment by ryanwjackson** [comment]
Not yet, besides record not found in Find operations.

--
Ryan Jackson
Product Manager
Modern Treasury ( https://www.moderntreasury.com )
