### ISSUE TITLE
Add resource support for Invoice (8 hrs)

### ISSUE THREAD

**Issue by mattgmarcus** [LedgerSync/ledger_sync#24]
https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/invoice

We need to be able to create, update, read, and delete invoices, including using Searchers for this

Attribute-wise, we need the following
- Id
- Line (can you figure out what we should support within Line, as there are a few ways this can be filled out)
- CustomerRef
- DocNumber
- TxnDate
- PrivateNote
- DepositToAccountRef
- Deposit
- InvoiceLink

**Comment by ryanwjackson** [comment]
@mattgmarcus What attributes do you want to be able to search by?

**Comment by mattgmarcus** [comment]
To start with we can just have an empty query. I'm not sure yet

**Comment by jozefvaclavik** [comment]
Done in https://github.com/LedgerSync/ledger_sync/pull/115
