### ISSUE TITLE
Remove sync class

### ISSUE THREAD

**Issue by ryanwjackson** [LedgerSync/ledger_sync#31]
**Is your feature request related to a problem? Please describe.**
The Sync class is a helper method that loosely wraps the functionality of an operation.  It helps with the composition of resources from a structured hash of data, adaptor, etc.  But in return it adds more complexity, such as `SyncResult` and that the utilities are buried by the `Sync` class.

**Describe the solution you'd like**
- Remove the `Sync` class and enable developers to build an operation themselves.
- Determine when/how to call the coordinator.  Perhaps this is just called from the `Performer` directly.  So flow would be to create an adaptor, create your resources (using the `Util::ResourcesBuilder` if desired), and creating the root `Operation`.  Then you would just use the `Performer` to call handle the `Operation`.

**Describe alternatives you've considered**
- Keeping the `Sync` class

**Additional context**
Should we make Sync accept `resources` and `resource` instead of `resources_data` and just have them use `Util::ResourcesBuilder`?

Should we rename "adaptor" to "ledger"?  They are ledgers, but does an adaptor imply the authentication attributes as well?

Is the `Sync` class necessary?

- `.operations` does give you the ordered list
- `SyncResult` does not add much value, and we could get rid of it.
- We could add `:resources` to the `Operation` initializer and it could handle building child operations by passing that down.

- coordinator would need to move.

@mattgmarcus @jozefvaclavik Would love your feedback.

**Comment by mattgmarcus** [comment]
I know less about the inner workings of this, so i trust you if this is a better solution.
Do you have a sense for how hard it'll be to refactor to this? 

Also, on `Remove the Sync class and enable developers to build an operation themselves`

**Comment by ryanwjackson** [comment]
@mattgmarcus it's not hard to refactor really.  The `Sync` class just takes structured primitives and creates an `Adaptor`, `Resources`, and `Operations`.  It does this using utilities, so really it's a wrapper for essentially ~10 lines of code.

Having the `Sync` class also means we need a special type of result, though perhaps the solution here is just to return an `OperationResult` and throw away the `SyncResult` classes.

My thought is that it's actually somewhat harder for a developer as-is because you have to explain how to structure data in primitives where I think that it makes more sense to say:

1. Create an `Adaptor` (which has it's own set of rules based on the ledger)
2. Create your resources (you can use the same utility `Util::ResourcesBuilder` and pass the structured primitive data or you can just build them yourself).
3. Create your operation(s) (which is just passing the adaptor and resource(s))

Then you use the `Util::OperationPerformer` to perform the operation(s) and you're done.

While more "steps," I find it more intuitive than "OK, build all these hashes in this way..."  And it's likely that at some point you would do it manually outside the sync class anyway.

I'm not sold on this, but just trying to reduce complexity.
