### ISSUE TITLE
Refactor resource attributes

### ISSUE THREAD

**Issue by ryanwjackson** [LedgerSync/ledger_sync#36]
**Is your feature request related to a problem? Please describe.**
Resource attributes are defined at the root of the resource, and we run the risk of conflicting with lib-specific attributes like `ledger_id`, `external_id`, `created_at`, etc.

**Describe the solution you'd like**
- Enable `resource.attributes` to respond with the resources attributes, excluding `ledger_id` and `external_id`.  So instead of `customer.phone_number`, it would be `customer.attributes.phone_number`.

**Describe alternatives you've considered**
- Not scoping
- Only handle in serialization.

**Related to**
- #8

**Comment by ryanwjackson** [comment]
Another case where attributes have their own "settings": #37

**Comment by ryanwjackson** [comment]
Rails has something like this: https://github.com/rails/rails/blob/master/activemodel/lib/active_model/attribute.rb

We are moving that direction in some ways.

One minor counter to burying under `attributes` is that there's still a conflict with `attributes` then (haha).  Especially if we are allowing passing attributes into `new()` directly like Rails does with models.

**Comment by mattgmarcus** [comment]
The interface for the API already has the attributes separated from the lib-specific attributes. So I'm not sure if I see the need for an interface change there. 

Also, is this just protecting against a future problem or is this a problem today?

**Comment by ryanwjackson** [comment]
That change is a future problem, but it would be a pretty breaking change
to update later.  Was just trying to think of what is correct today, given
that we have to update how we handle the attributes anyway.


--
Ryan Jackson
ryanwjackson@gmail.com

**Comment by mattgmarcus** [comment]
Ok. I agree if what you're describing took place it'd be a big change...I'm still not sure if I follow it. Could you paste in the API calls I'd do before and after?
