### ISSUE TITLE
Add x_refresh_token_expires_in to QBO attributes_to_save

### ISSUE THREAD

**Issue by ryanwjackson** [LedgerSync/ledger_sync#48]
- [ ] Ensure we are saving all the updated parameters (including `x_refresh_token_expires_in`): https://developer.intuit.com/app/developer/qbo/docs/develop/authentication-and-authorization/oauth-2.0
- [ ] Document `attributes_to_save` and psuedocode for when to save.

**Comment by mattgmarcus** [comment]
@ryanwjackson  I noticed that the `expires_at` field is often `nil`. Just wanted to double check that it isn't a typo
