### ISSUE TITLE
Create tool to do oauth flow locally 

### ISSUE THREAD

**Issue by mattgmarcus** [LedgerSync/ledger_sync#59]
**Is your feature request related to a problem? Please describe.**
Currently it's pretty hard to test out the oauth flow with the lib on its own. This is because you need to have a server running that can take the callback from QBO.

**Describe the solution you'd like**
We should have a little puma script or something we can run within the lib's directory. I think we only need 1 endpoint on there to take the callback, return a 200, and spit out to the logs the access token. 
You may have to do #58 first since that will take care of a lot. I imagine the flow would be something like

1. In one terminal window, start the server
2. In the other terminal window, start a rails console, and call something like `QBOUtils.generate_qbo_url(client_id: blah, client_secret: blah)`. Get the URL and visit it in your browser

Then once you do the flow, the eventual credentials should spit out in the server. I guess a bonus would be if it came with the pre-populated command you needed, like a call you could copy to instantiate the adaptor given what had just come back

**Comment by mattgmarcus** [comment]
@ryanwjackson sorry I think i'm half coherent now, so let me know if you need clarification

**Comment by ryanwjackson** [comment]
@jozefvaclavik Want to take a stab at this first?  You can also steal from `qa.rb` which does the token management yaml stuff.
