### ISSUE TITLE
Utilities for processing webhooks

### ISSUE THREAD

**Issue by mattgmarcus** [LedgerSync/ledger_sync#66]
**Is your feature request related to a problem? Please describe.**
QBO can send you webhooks. I'd like some helper functions to help out with processing these.
The webhooks are generally pretty unspecific. It just gives you a body like this
```
{
   "eventNotifications":[
   {
      "realmId":"1185883450",
      "dataChangeEvent":
      {
         "entities":[
         {
            "name":"Customer",
            "id":"1",
            "operation":"Create",
            "lastUpdated":"2015-10-05T14:42:19-0700"
         },
         {
            "name":"Vendor",
            "id":"1",
            "operation":"Create",
            "lastUpdated":"2015-10-05T14:42:19-0700"
         }]
      }
   }]
}
```
https://developer.intuit.com/app/developer/qbo/docs/develop/webhooks/managing-webhooks-notifications

They also include a token you can use to verify that it's from them

**Describe the solution you'd like**
I need a way to verify the request came from QBO. I expect the method signature is something like
```
def verify_quickbooks_token(verifier_token, request_body) --> returns true/false
```
I'm not sure what you pass in exactly. Probably the whole body.

**Describe alternatives you've considered**
Do we want a lightweight function that just translates the body into ledgersync resources
```
def parse_webhook(webhook_body)

--> returns
{
  realm_id: realm_id,
  entities: [array of ledgersync entities with their ledger_id],
}
```

I'm not sure if that would really be helpful. Plus we still have to capture the event action (create, delete, etc).

We could add a way to do a `Find` on the entity automatically but you could do that yourself too as the consumer.

Originally I was leaning towards doing this but not I'm not. Thoughts @ryanwjackson ?

**Comment by ryanwjackson** [comment]
@mattgmarcus We can handle the verification, but we could also add `QuickBooksOnline::Webhook` and `QuickBooksOnline::WebhookEvent` class that can do both the verification and parsing.  With that you could get something like `webhook.events.first.operation` and probably event `webhook.events.first.resource(s)`.

Thoughts?

**Comment by mattgmarcus** [comment]
Yeah I think that would be nice. What would `.operation` return though?

**Comment by ryanwjackson** [comment]
Oh, good question.  Not our operation.  I was just reading their key.  We could call it `quickbooks_method`.  I'm basing this solely on the sample webhook you sent.  Probably worth looking at a few more to make sure they all follow that structure.
