### ISSUE TITLE
Add support for Payment resource

### ISSUE THREAD

**Issue by mattgmarcus** [LedgerSync/ledger_sync#77]
https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/payment

We need support for `Payment`

Fields I'd want
- Id
- TotalAmt
- CustomerRef
- CurrencyRef
- PrivateNote
- DepositToAccountRef
- ExchangeRate
- Line (with support for associations to Expense, JournalEntry, and Invoice)
- ARAccountRef
- PaymentRefNum
- TxnDate

**Comment by mattgmarcus** [comment]
@jozefvaclavik - this one is the highest priority, so if you were able to wrap it up by end of week, that would be appreciated

**Comment by ryanwjackson** [comment]
@jozefvaclavik says this depends on #24 as you need to be able to associate an invoice with the payment.

**Comment by jozefvaclavik** [comment]
Done in https://github.com/LedgerSync/ledger_sync/pull/115
