### ISSUE TITLE
Add the resource's ledger URL to the attributes

### ISSUE THREAD

**Issue by mattgmarcus** [LedgerSync/ledger_sync#79]
I would like a way to, given a resource, call `resource.ledger_url` and get back the URL for it in the ledger. For example if it were an expense, 
`https://app.sandbox.qbo.intuit.com/app/expense?txnId=149`

**Comment by mattgmarcus** [comment]
@ryanwjackson @jozefvaclavik - thoughts?

**Comment by ryanwjackson** [comment]
There is a stubbed out function for this actually. But it would be `adaptor.url_for(resource: customer)`

We just need the urls to be structured the same and know the mapping of what we call our lib resources to what they call their resources (e.g. an expense to us is a purchase to them). 

But we can at least default to our definition with manual overrides if necessary. Or we can rely on the new serializers which also use this information and override where necessary (assuming QBO keeps it the same).

**Comment by mattgmarcus** [comment]
Gotcha, yea that's fine to call it thru the adaptor. 

It might be better to just force us to be explicit, so that we don't make assumptions/it's easier to figure out what's going on.

**Comment by mattgmarcus** [comment]
https://app.sandbox.qbo.intuit.com/app/recvpayment?txnId=155
https://app.sandbox.qbo.intuit.com/app/customerdetail?nameId=1
