### ISSUE TITLE
Make resources know what attributes were set

### ISSUE THREAD

**Issue by ryanwjackson** [LedgerSync/ledger_sync#8]
**Is your feature request related to a problem? Please describe.**
When you set an attribute to `nil` (or maybe event `''`), it ignores that value and uses the ledger's current value.  Because of this, you can never _unset_ an attribute in the ledger.

**Describe the solution you'd like**
The resources should know which attributes have been updated (similar to ActiveModel Dirty functions), so that if a value is set to `nil` the resulting API call will include a `null`.

**Comment by ryanwjackson** [comment]
When doing this, we need to ensure that in `temp_app` all of the following succeed assuming that vendor is a required attribute of expense

- Sync a new expense (a.k.a. create) where you reference an existing vendor only by `external_id` and no other attributes.  The vendor should be associated to the expense but not updated.
- Sync an existing expense (a.k.a. update) where you reference an existing vendor only by `external_id` and no other attributes.  The vendor should not be updated.
- Sync an existing expense (a.k.a. update) where the vendor is not supplied at all.

**Comment by mattgmarcus** [comment]
Looks good, thanks Ryan

**Comment by ryanwjackson** [comment]
Ref:
- https://api.rubyonrails.org/classes/ActiveModel/Dirty.html
- https://github.com/rails/rails/blob/66cabeda2c46c582d19738e1318be8d59584cc5b/activemodel/lib/active_model/dirty.rb
- https://github.com/rails/rails/blob/66cabeda2c46c582d19738e1318be8d59584cc5b/activemodel/lib/active_model/attribute_methods.rb#L65
- https://github.com/rails/rails/blob/66cabeda2c46c582d19738e1318be8d59584cc5b/activesupport/lib/active_support/concern.rb
